#################################
#                               #
#   Code generated by Edsim++   #
#                               #
#################################

# R       : https://cran.r-project.org/
# Rtools  : https://cran.r-project.org/bin/windows/Rtools/
# RxODE   : https://cran.r-project.org/web/packages/RxODE/index.html
# nlmixr  : https://cran.r-project.org/web/packages/nlmixr/index.html

# Load RxODE (requires RTools)
library(RxODE)

# Start of model (C-Language)
ode = "

  # Standard Equations
  Age  = P01_Age + t / 365.0 / 24.0;
  Bw   = P01_Bw;
  C01_Cu = C01_A / C01_V;
  MW_ALB = 66500;
  MW_CBG = 55000;
  MW_COR = 362.46;
  F   = C01_Cu   / MW_COR * 1E6;
  TA  = C01_ALB  / MW_ALB * 1E6;
  TC  = C01_CBG  / MW_CBG * 1E6;
  TCI = (1 - C01_RC) * TC;
  TCE = C01_RC * TC;
  KA  = C01_Kca  / MW_ALB * 1E6;
  KCI = C01_Kci  / MW_CBG * 1E6;
  KCE = C01_Kce  / MW_CBG * 1E6;
  TF  = F * (1 + TA / (KA + F) + TCI / (KCI + F) + TCE / (KCE + F));
  C01_fu = F / TF;
  C01_C  = C01_Cu / C01_fu;
  PO_R = PO_k * PO_A;
  ME_k = ME_CL / C01_V;
  ME_R = ME_k * C01_A;
  fu_Var = C01_fu;

  # Differential Equations
  d/dt(C01_A) = (+PO_R) + (-ME_R);
  d/dt(PO_A) = (-PO_R);
  d/dt(AUCU_AUC) = C01_Cu;
  d/dt(AUC_AUC) = C01_C;

"
# End of model

# Compile the model
mod = RxODE(model = ode, modName = "mod", wd = "data")

# Initialize parameters
parm = c(P01_Age = 55,P01_Bw = 70,C01_CBG = 44,C01_ALB = 44555,C01_Kca = 21945,C01_Kci = 1.815,C01_Kce = 18.15,C01_RC = 0.1,C01_V = 474.38,PO_k = 1.4,ME_CL = 235.78)

# Initialize variables
vini = c(C01_A = 0,PO_A = 0,AUCU_AUC = 0,AUC_AUC = 0)

# Create lookup vectors for differential variables (vdif), observed variables (vobs) and vobs units (uobs).
vdif = unlist(strsplit("C01_A,PO_A,AUCU_AUC,AUC_AUC",","))
vobs = unlist(strsplit("C01_C,C01_Cu,C01_fu",","))
uobs = unlist(strsplit("mg/L,mg/L,-",","))

# Create event table
ev = eventTable(amount.units='mg', time.units='hours')

# Set output range
# ev$add.sampling(0:30)
ev$add.sampling(seq(0, 30, by=0.1))

# Add dosing events (all code in objects starting with ~ is appended and expanded here after)
ev$add.dosing(dose=10 * 0.96, start.time=0, nbr.doses=3, dosing.interval=6, dosing.to=which(vdif=="PO_A"))

# Execute simulation
result = mod$run(parm, ev, vini)

# Save results (remove comment and change path)
# write.csv(result,'result.csv')

# View results table
#View(result)
fresult=result[,c("time", "C01_C", "C01_Cu", "C01_fu")]
colnames(fresult)<-c("t", "C", "Cu", "fu")
View(fresult)

#Save data for use in shiny
save(mod, parm, ev, vini, vdif, vobs, uobs,file = "data/data.rda")